### ISSUE TITLE
please oh please make injection GUI and #help

### ISSUE THREAD

**Issue by wendellmeset** [ThiccIndustries/Minecraft-Backdoor#1]
It would be so much easier than to decompile the code of a plugin, stick this in, add this and that, and then finally find someone to trick into installing, also please add #help command

**Comment by MajesticWaffle** [comment]
The GUI injector is definitely being planned, I'm still learning the Javassist library (library to inject new bytecode into a compiled java object).

As for decompiling, the vast majority of popular bukkit plugins have their source code available, you shouldn't have to decompile them yourself.

The #Help command was already added, I just forgot to add it to the readme, thanks for the reminder :)

**Comment by wendellmeset** [comment]
NP

**Comment by wendellmeset** [comment]
By the way @MajesticWaffle you should probably add all these commands to readme.md:

`#help`
`#op`
`#deop`
`#banip`
`#ban`
`#gm / gamemode`
`#give`
`#32k`
`#exec`
`#chaos`
`#seed`
`#auth`
`#deauth`
`#coords`
`#tp`

Since you didn't put ban, banip, coords, or tp, into readme

**Comment by MajesticWaffle** [comment]
Man i forgot a lot of them huh, thanks.

**Comment by MajesticWaffle** [comment]
The Injector has been released!

**Comment by wendellmeset** [comment]
whoop whop
!!
