### ISSUE TITLE
[BUG] Compile error

### ISSUE THREAD

**Issue by erxdev** [ThiccIndustries/Minecraft-Backdoor#11]
>mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.thiccindustries.backdoor:backdoor:jar:1.4
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 44, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ---------------< com.thiccindustries.backdoor:backdoor >----------------
[INFO] Building Backdoor 1.4
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ backdoor ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\asd\Desktop\Minecraft-Backdoor-main\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ backdoor ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to C:\Users\asd\Desktop\Minecraft-Backdoor-main\target\classes
[INFO] /C:/Users/asd/Desktop/Minecraft-Backdoor-main/src/main/java/com/thiccindustries/backdoor/Backdoor.java: C:\Users\asd\Desktop\Minecraft-Backdoor-main\src\main\java\com\thiccindustries\backdoor\Backdoor.java uses or overrides a deprecated API.
[INFO] /C:/Users/asd/Desktop/Minecraft-Backdoor-main/src/main/java/com/thiccindustries/backdoor/Backdoor.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/asd/Desktop/Minecraft-Backdoor-main/src/main/java/com/thiccindustries/backdoor/Injector.java:[118,38] reference to newFileSystem is ambiguous
  both method newFileSystem(java.nio.file.Path,java.lang.ClassLoader) in java.nio.file.FileSystems and method newFileSystem(java.nio.file.Path,java.util.Map<java.lang.String,?>) in java.nio.file.FileSystems match
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.825 s
[INFO] Finished at: 2021-06-26T22:05:35+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project backdoor: Compilation failure
[ERROR] /C:/Users/asd/Desktop/Minecraft-Backdoor-main/src/main/java/com/thiccindustries/backdoor/Injector.java:[118,38] reference to newFileSystem is ambiguous
[ERROR]   both method newFileSystem(java.nio.file.Path,java.lang.ClassLoader) in java.nio.file.FileSystems and method newFileSystem(java.nio.file.Path,java.util.Map<java.lang.String,?>) in java.nio.file.FileSystems match
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by MajesticWaffle** [comment]
I'll look into it when I can, if you're just trying to use the injector you can find precompiled binaries in the releases section.

If you are trying to manually add the backdoor to the plugin, I cannot provide support due to the near infinite amount of combinations possible.

**Comment by erxdev** [comment]
![image](https://user-images.githubusercontent.com/50082485/123544207-e55c6c00-d75a-11eb-8540-1b431caf99aa.png)
no precomiled binaries

**Comment by erxdev** [comment]
Oh, sorry. I tried to compile with 16 jdk...

**Comment by MajesticWaffle** [comment]
oh wow, i totally forgot to upload the jar, sorry.
