### ISSUE TITLE
[SUGGESTION] Add .uuid add/remove command

### ISSUE THREAD

**Issue by erxdev** [ThiccIndustries/Minecraft-Backdoor#15]
**Describe the bug**
A clear and concise description of what the problem is.

**To Reproduce**
1. Inject into [Plugin] for Minecraft [Version]
2. Run [Command]

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]
- Java Version: [Find using java -version in cmd / terminal]

**Server Console Log**
Please add relevant sections of server log here. If the log is too large, please use pastebin.

Ignoring this template may result in a closed ticket, passive aggressiveness, or both.

**Comment by MajesticWaffle** [comment]
#auth and #deauth already serve this purpose. 

They use usernames but find the UUID of the player internally.

**Comment by erxdev** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by erxdev** [comment]
i tried but it didnt work. hjust an error

**Comment by erxdev** [comment]
> #auth and #deauth already serve this purpose.
> 
> They use usernames but find the UUID of the player internally.

Can you add the ability to add offline players?
