### ISSUE TITLE
How do you use #exec?

### ISSUE THREAD

**Issue by DlPEK** [ThiccIndustries/Minecraft-Backdoor#21]
I'm guessing im typing the command to execute wrong

**Comment by MajesticWaffle** [comment]
#exec [command]

Everything in [command] will be executed as if it were pasted into the server console.

**Comment by MajesticWaffle** [comment]
Don't preface your command with '/' like you would for a client command. Server consoles don't have any command prefix.

Examples

``#exec say hi``

Will result in ``say hi`` being "entered into" the console,

Which results in the console executing ``/say hi``

**Comment by DlPEK** [comment]
Oh so it doesn't work correctly, it doesn't work

**Comment by DlPEK** [comment]
I tested and the plugin doesn't recognize #exec as a command i think.

**Comment by MajesticWaffle** [comment]
If its still not working please provide the following so I can test it:

Operating system & Version (Ex: Windows 10):
Java Version (type ``java -version`` into your cmd / terminal):
Minecraft version (Ex: 1.16.5, 1.12.2):
Plugin injected:

If you are testing this on your own local server, please upload a server log to pastepin containing the result of running the #exec command.
