### ISSUE TITLE
[SUGGESTION] Add package obfuscation.

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#22]
com/backdoor - bad idea :(
You can just detect main directory and implent backdoor there

**Comment by RandomVersion** [comment]
> com/backdoor - bad idea :(
> You can just detect main directory and implent backdoor there

true

**Comment by qualk** [comment]
Yea, not using until this feature implemented.

**Comment by RandomVersion** [comment]
> Yea, not using until this feature implemented.

well unless you give it to like your friend or somebody who dosnt know how to look tru the src its good
