### ISSUE TITLE
[SUGGESTION] Add "Auto find UUID from nickname" checkbox

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#23]
Im putting nickname and it will convert it to 2 UUIDs (License + Cracked).

**Comment by MajesticWaffle** [comment]
Version 1.5 implements a username mode. 

Finding the UUID automatically would require either some sort of API to find it at inject time, or giving "dibs" to whomever connects with that username first. Usernames should only be used in place of UUIDs on cracked servers, as they are inherently less secure.
