### ISSUE TITLE
[BUG] Update "manual injection guide" (its doesnt since u made multiUUID)

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#24]
"new backdoor(blabla, **String[]** {"blabla"}, blabla);"

**Comment by MajesticWaffle** [comment]
Done

**Comment by erxson** [comment]
maybe [""]? 
![image](https://user-images.githubusercontent.com/50082485/131855459-89ecc4cd-a5c4-4709-a3e2-f9aabb679e77.png)
