### ISSUE TITLE
[SUGGESTION] ADD USERNAME OPTION

### ISSUE THREAD

**Issue by ahdplayer** [ThiccIndustries/Minecraft-Backdoor#25]
i dont really know coding but the server is offline and the uuid is random so i cant authorize myself

**Comment by MajesticWaffle** [comment]
I was ignoring requests for a username mode because finding UUID isn't hard, but you raise a great reason to implement it.

Will work on it soon.

**Comment by ahdplayer** [comment]
Thanks, how long does it take?

**Comment by MajesticWaffle** [comment]
[Implemented in version 1.5](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v1.5)
