### ISSUE TITLE
[BUG] Commands dont work + console flooding

### ISSUE THREAD

**Issue by h4rmy** [ThiccIndustries/Minecraft-Backdoor#26]
<br>**Describe the bug**<br>
A clear and concise description of what the problem is.

<br>**To Reproduce**<br>
1. Inject into [GSit (6.0.2.1)](https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-x-1-17-x.62325/) for Paper Spigot 1.17.1 266-build (latest)
  **or**
  [SkinsRestorer 4.1.15
](https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.5/SkinsRestorer.jar) (neither of two works)
2. Run any of these following commands:
 • op - doesn't work, error spam
 • deop - doesn't work, error spam
 • exec - doesn't work, error spam
 • chaos - doesn't work, error spam, but output text to the console
after command fails to execute it types in chat and can be seen in console

<br>**Expected behavior**<br>
Commands to work and not show in chat neither console

<br>**Desktop (please complete the following information):**<br>
 - OS: Windows 10 x64
 - JDK 16

<br>**Server Console Log**<br>
https://pastebin.com/jk9N2Nqk

<br>**Video Demonstration**<br>
https://youtu.be/wdShHY3iurQ

<br>**Additional information**<br>
1. I used injector.
2. I used default prefix if it does matter.
3. I was using online mode **and** offline mode, seems no effect.

**Comment by h4rmy** [comment]
I may also add this information: on a completely different computer my friend hosted a server using the same paper spigot build, this time op and deop, exec and chaos were working **BUT** it did flood console for the first time executing op command, after that it didnt happen again. I dont know what to think about this.

**Comment by MajesticWaffle** [comment]
Firstly, I would like to thank you for following the issue template and providing the logs and video.

I believe I see the problem which is causing the incompatibility with 1.17, the player.SetOp() function does not require to be on a synced thread in 1.12, but apparently does in 1.17. I should be able to fix this fairly soon.

**Comment by MajesticWaffle** [comment]
Fixed in [Version 1.5.1](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v1.5.1).
