### ISSUE TITLE
[suggsetion] add custom backdoor directory (and custom classname, because this backdoor is so fucking unlegit)

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#28]

**Comment by MajesticWaffle** [comment]
This backdoor works by copying pre-compiled .class files. For technical reasons, renaming them at runtime would be a headache.

If you want the files to have a different name. Spend all your time and energy you use to create "issue" requests that aren't actual issues, and take 20 seconds to press the big "Fork" button right in the center right of your screen, you can't miss it! From there, you can rename the files to whatever you fucking want.

If you can't figure out how to compile the Java project, I recommend the following resources:

[Resource](www.google.com)
[Resource](www.duckduckgo.com)
[Resource](www.bing.com)
