### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Epik123** [ThiccIndustries/Minecraft-Backdoor#29]
add console lock, and plugin downloader and deleter to the backdoor mabye?

**Comment by MajesticWaffle** [comment]
I do not know of a way for a spigot plugging to lock the console.

I'm not sure what a "plugin downloader" is. If you're suggesting the ability to download server files, that would require ftp access.

**Comment by Epik123** [comment]
https://github.com/Epik123/Cyanide u can lock and download plugins to the server thats backdoored through this no ftp

**Comment by MajesticWaffle** [comment]
Ohh you want the ability to download files to the server? I thought you were asking for a way to download server files. I'll look into it.

**Comment by Epik123** [comment]
yeah sorry lol

**Comment by MajesticWaffle** [comment]
I'll look into possible implementations. Discord bot integration is pretty beyond the scope of this project, so I'll mess around with other options.

**Comment by Epik123** [comment]
yeah ive saw it done completely ingame before no discord integration

**Comment by Epik123** [comment]
> > I'll look into possible implementations. Discord bot integration is pretty beyond the scope of this project, so I'll mess around with other options.
> 
> just add discord integration please. if you add it we can upload backdoored plugin to spigotmc and when someone run it we can see from discord webhook and grief it.

stfu
