### ISSUE TITLE
[BUG] Backdoor always fails

### ISSUE THREAD

**Issue by wink05** [ThiccIndustries/Minecraft-Backdoor#30]
<br>**Describe the bug**<br>
Hi, I was trying to use this plugin at few plugins, unfortunately all of them shows same error "## Backdoor ## Command execution failed." I tried with: EssentialsX, EssentialsXChat, AuthMe, RandomTP, BetterSleeping4

<br>**To Reproduce**<br>
1. Inject into ANY OF PLUGIN I MENTIONED EARLIER for Minecraft 1.17.1 (paper version git-Paper-295)
2. Run any of the command
3. Hopefully  see error

<br>**Expected behavior**<br>
I just expected everything to work just fine, maybe not at first time but at some plugin I expected it to work.

<br>**Desktop (please complete the following information):**<br>
- OS: both server and client are at Windows 10.
- Java Version for Server: openjdk version "17" 2021-09-14 LTS
- Java Version for Client: java version "1.8.0_301"

<br>**Server Console Log**<br>
Unfortunately got absolutely no logs. All loads just fine, plugins too, no additional backdoor output.
I can still upload if needed.

**Comment by MajesticWaffle** [comment]
That's very strange, testing on versions >1.12.2 has been very limited. What commands have you tried?

**Comment by wink05** [comment]
Hi! Thanks for reply! I tried almost all commands, but mostly I tried op, deop, gm, give, ban, tp, coords, seed, exec so almost all of available commands.

**Comment by MajesticWaffle** [comment]
Well that's strange, I'll look into it when I'm able to, should be around Sunday.

**Comment by wink05** [comment]
Hey, any update? :D

**Comment by Epik123** [comment]
> Hey, any update? 

it works fine for me on all versions 1.12 and above what are u using username or uuid

**Comment by wink05** [comment]
> > Hey, any update?
> 
> it works fine for me on all versions 1.12 and above what are u using username or uuid

Currently I'm using UUID while injecting

**Comment by MajesticWaffle** [comment]
I'm not able to reproduce this problem myself. Can you please upload a patched plugin jar produced with the injector so I can decompile it and see what is going wrong?

**Comment by MajesticWaffle** [comment]
> I'm not able to reproduce this problem myself. Can you please upload a patched plugin jar produced with the injector so I can decompile it and see what is going wrong?

If you do not want to share your Minecraft account, patch something with a fake UUID

**Comment by MajesticWaffle** [comment]
> I'm not able to reproduce this problem myself. Can you please upload a patched plugin jar produced with the injector so I can decompile it and see what is going wrong?

If you do not want to share your Minecraft account, patch something with a fake UUID

**Comment by wink05** [comment]
> I'm not able to reproduce this problem myself. Can you please upload a patched plugin jar produced with the injector so I can decompile it and see what is going wrong?

Here you go: https://drive.google.com/file/d/14m5PI-BPR9hSnD4ICDFHZg2ckhl228Rm/view?usp=sharing

**Comment by PerchunPak** [comment]
Fixed it by setting default prefix, seems like custom prefixes doesn't working

**Comment by PerchunPak** [comment]
> Fixed it by setting default prefix, seems like custom prefixes doesn't working

And it is because command check for prefix from [Config.java](https://github.com/ThiccIndustries/Minecraft-Backdoor/blob/main/src/main/java/com/thiccindustries/backdoor/Config.java) which change only on compile plugin.

**Comment by PerchunPak** [comment]
So temp fix is use 1 letter prefix, I will create pl which will fix this

**Comment by PerchunPak** [comment]
Developer doesn't merge my PL for 15 hours, so i create [pre-build binaries](https://github.com/PerchunPak/Minecraft-Backdoor/releases/tag/v1.5.1cp) for those who want use it right now.
Also remember that you need check it three times before use something from unknown sources.
