### ISSUE TITLE
Backdoor doing nothing.

### ISSUE THREAD

**Issue by Watermelon1245** [ThiccIndustries/Minecraft-Backdoor#35]
Hi, i installed the injector, injected simple tpa and downloaded the plugin on to my minecraft server, when i join the server nothing happens. What is supposed to happen after i have the plugin installed and i join a server?

**Comment by erxson** [comment]
you could use invalid uuid in injector

**Comment by LiamRay10** [comment]
dos anyone have a totarl on how to do this

**Comment by oliver408i** [comment]
You have to use the commands. Try using #help Or #op

**Comment by MajesticWaffle** [comment]
If you are using a command prefix with a length > 1 be sure to download the newest version of the injector [here](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v1.5.2).
If that's not the problem, a server log would be helpful.

**Comment by MajesticWaffle** [comment]
Closed - Inactive
