### ISSUE TITLE
Works fine on MacOS

### ISSUE THREAD

**Issue by oliver408i** [ThiccIndustries/Minecraft-Backdoor#36]
The description says that the jar doesn't work on MacOS, however, I am on a mac and I can use it fine. There is just the catch that you have to do it through the terminal by using `java -jar <name of the file>`(try with sudo if needed) Double click doesn't work. It just doesn't show the select file screen.

**Comment by MajesticWaffle** [comment]
When you do launch it using the console, does it open the file select screen?

**Comment by oliver408i** [comment]
yes
![image](https://user-images.githubusercontent.com/75344601/141668803-c9d10519-976e-4146-b6d2-7c0c91cd6bd0.png)

**Comment by oliver408i** [comment]
However I am on a pretty old version of macOS (10.13 High Serra)

**Comment by MajesticWaffle** [comment]
Mac OS is very strange, Ill change the readme to mention running though the terminal.
