### ISSUE TITLE
Plugin detected WITHOUT any malware detectors

### ISSUE THREAD

**Issue by oliver408i** [ThiccIndustries/Minecraft-Backdoor#38]
Pebble Host can detect it. It's not invisible :)
![image](https://user-images.githubusercontent.com/75344601/142551689-20ecfce4-06f3-472c-bb89-54172c52cca3.png)

**Comment by MajesticWaffle** [comment]
Bound to happen eventually. I'm curious if its simply a CTRL-F for "Backdoor".

**Comment by MajesticWaffle** [comment]
Maybe fixed with [version 1.6](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v1.6).

**Comment by oliver408i** [comment]
idk

**Comment by PerchunPak** [comment]
> idk

@oliver408i test it, or please close issue
