### ISSUE TITLE
Half the commands dont work

### ISSUE THREAD

**Issue by wendellmeset** [ThiccIndustries/Minecraft-Backdoor#4]
half the commands dont work and put HUGE errors in the console, dont ask me to send them

**Comment by wendellmeset** [comment]
Wait also

**Comment by wendellmeset** [comment]
@MajesticWaffle can you make a separate project that allows you to inject ANYTHING you want  into ANY jar, please? In return ill give you a really really cool thing that goes on your github page, and it makes it look awesome

**Comment by wendellmeset** [comment]
@MajesticWaffle And it shows your github stats, most used coding language, and info

**Comment by wendellmeset** [comment]
@MajesticWaffle just check my profile page and it looks like that

**Comment by wrapfield** [comment]
Hi, this is Austin at Thicc Industries.

This is a known issue that we're looking into, this was initially tested primarily with the defacto multiplayer version of Minecraft, Java 1.12.2. We cannot guarantee this will work for anything else but it's in the works. Pinging will not make us fix it any faster.

If you want to inject anything into any .JAR file, look into a project called 7-zip. Abuse of issue tickets in which you pan-handle for software will result in us just closing them.

**Comment by MajesticWaffle** [comment]
1: I can't fix a problem when all you give me is "It doesn't work". Ive tested multiple plugins across both 1.12.2 and 1.16.5 and I've never had an issue beyond the initial 1.2 windows incompatibility.

2: Ha ha no.

Unless you want to contribute actual information on your problem, fix it yourself.

**Comment by wendellmeset** [comment]
Im very sorry, I just love the idea of this plugin

**Comment by MajesticWaffle** [comment]
> Im very sorry, I just love the idea of this plugin

Thats fine, but if you want us to fix your issue you need to give us information.

What plugin did you try?
What minecraft server version (1.16, 1.12, etc)?
What command(s) don't work?

**Comment by wendellmeset** [comment]
The server version was 1.16.5, the plugin i tried was clearlag, and i cant remeber exact broken commands, but i think it was tp, and a few more, ill check again in few mins

**Comment by wendellmeset** [comment]
@MajesticWaffle

**Comment by MajesticWaffle** [comment]
I've looked into this and it seems to come from changes spigot has made in 1.16. unfortunately fixing it would break 1.12 which frankly is more important to us.

I encourage you to fork the project if you want to make a better 1.16 version.

It seems #tp needs to be wrapped into a Thread safe BukkitRunnable (see the gamemode command for example)

I'm not sure what's wrong with the others.
