### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Potato2541** [ThiccIndustries/Minecraft-Backdoor#45]
Injected the plugin.
Tried using the plugin
Wrote #op but didnt do anything
Using spigot 1.18 server on minehut
In console, it just says [Async Chat Thread - #0/INFO]: <My Username> #op
and doesnt do anything

The plugin I injected is orebfuscator plugin 5.2.0

**Comment by PerchunPak** [comment]
Please provide full log from logs/latest.log
Also don't forget paste your logs on pastebin sites, like https://pastebin.org

**Comment by MajesticWaffle** [comment]
Closed for inactivity.
