### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Arinji2** [ThiccIndustries/Minecraft-Backdoor#48]
Hello i just wanted to know will it not work if i remove the patched part like the (plugin name)-pathched.jar? And will this work in 1.18.1 plugins

**Comment by MajesticWaffle** [comment]
There shouldn't be any problems with 1.18.1, although it has not been tested.
I'm not sure what the first question means. 
If you are just asking if you can rename the file, the answer is yes.

**Comment by Arinji2** [comment]
okiii thanks
