### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Arinji2** [ThiccIndustries/Minecraft-Backdoor#49]
<br>Plugin doesnt work in some servers while it does in others<br>
A clear and concise description of what the problem is.

<br>**To Reproduce**<br>
1. Inject into BigDoors for Minecraft 1.18.1
2. I did two tests... one in a free server and the other paid.... the paid had alot of plugins the free one was empty. I uploaded the same .jar files to both. The plugin disabled in the paid one and worked on the other 

<br>**Expected behavior**<br>
To just work lol

<br>**Server Console Log**<br>
Free Server Log: https://pastebin.com/Wb1nx8fW
Paid Server lol: https://pastebin.com/PB9Zjyt1

Attached below are the normal plugin jar's and the injected ones. 
https://www.dropbox.com/s/4a1lrlgcpf36qbx/BigDoors-patched.jar?dl=0
https://www.dropbox.com/s/5qh1k1vnx0sbv4a/BigDoors.jar?dl=0

**Comment by nullsoepic** [comment]
Line 833 of Paid Server Log:
`[11:41:40] [Server thread/WARN]: [BigDoors] This plugin is disabled because it is running in an invalid environment: Geyser-Spigot`
The plugin simply doesn't work with Geyser, free server did not have the issue since as you said it was empty

**Comment by MajesticWaffle** [comment]
Try using the same plugin without the spreading feature enabled.

**Comment by Arinji2** [comment]
Yup it worked thankss

**Comment by MajesticWaffle** [comment]
@Arinji2 if you could add your setup and logs to issue #40 to help improve the spreading feature that would be great
