### ISSUE TITLE
[BUG] I can't inject it always fails what can i do to fix it

### ISSUE THREAD

**Issue by Discordhash** [ThiccIndustries/Minecraft-Backdoor#51]
"Unrecognized option: -Xlog:class+load=info:classloaded.txt
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."
https://prnt.sc/26k9r31

**Comment by Discordhash** [comment]
@MajesticWaffle

**Comment by MajesticWaffle** [comment]
You do not need to use that option unless you're helping debug the spreading feature.
To get that option to work you need to use a newer version of Java.

**Comment by Discordhash** [comment]
> You do not need to use that option unless you're helping debug the spreading feature. To get that option to work you need to use a newer version of Java.

Can you send me link i alr downloaded yesterday and still didn't work

**Comment by ThnksCJ** [comment]
> 

the dowload link is https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v2.2.1
