### ISSUE TITLE
Where is the injector

### ISSUE THREAD

**Issue by 2g2m** [ThiccIndustries/Minecraft-Backdoor#56]
how do i get the injector to inject my plugin. when i download i only see
.github
src
.gitattributes
.gitignore
LICENSE
pom
readme

**Comment by 2g2m** [comment]
@MajesticWaffle help please

**Comment by 2g2m** [comment]
nevermind i found it

**Comment by 2g2m** [comment]
@MajesticWaffle @PerchunPak what verisions does it work on

**Comment by PerchunPak** [comment]
Please don't use this as just a chat.

Versions: any. Any means any minimum actual versions, including 1.12 and 1.18. Other versions I didn't test, if you find issue - you free to report it in new issue report.

Close it please.
