### ISSUE TITLE
[BUG] Spread error

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#63]
[classloaded.txt](https://github.com/ThiccIndustries/Minecraft-Backdoor/files/8302833/classloaded.txt)
error log: 
[Injector] Injecting resources.
    (1/182) Debugger.class
    (2/182) Debugger$1.class
    (3/182) Debugger$2.class
    (4/182) Debugger$3.class
    (5/182) Debugger$4.class
    (6/182) Debugger$5.class
    (7/182) Debugger$6.class
    (8/182) Debugger$7.class
    (9/182) Debugger$8.class
    (10/182) Debugger$9.class
    (11/182) Debugger$10.class
    (12/182) Debugger$11.class
    (13/182) Debugger$12.class
    (14/182) Debugger$13.class
    (15/182) Debugger$FileBuffer.class
    (16/182) Config.class
    (17/182) Config$HelpItem.class
    (18/182) Injector.class
    (19/182) Injector$SimpleConfig.class
    (20/182) ClassPath.class
    (21/182) ClassPool.class
    (22/182) NotFoundException.class
    (23/182) CannotCompileException.class
    (24/182) CtClass.class
    (25/182) CtArray.class
    (26/182) CtClassType.class
    (27/182) CtNewClass.class
    (28/182) CtNewNestedClass.class
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.nio.file.Files.copy(Files.java:3128)
        at com.thiccindustries.debugger.Injector.patchFile(Injector.java:135)
        at com.thiccindustries.debugger.InjectorGUI.main(InjectorGUI.java:123)

**Comment by MajesticWaffle** [comment]
Thats very strange that a random file in the JavaAssist Library would fail, let me look into that

**Comment by MajesticWaffle** [comment]
Could you please send the link to the plugin you were using, your OS and Java versions as well as if you were using online or offline mode?

**Comment by erxson** [comment]
[ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/)
Windows 64bit
JDK 17
Offline mode

**Comment by MajesticWaffle** [comment]
Unfortunately I was not able to reproduce your issue. It sounds like one of the resources inside the javassist library is missing, try redownloading the injector?

**Comment by erxson** [comment]
Sorry, my bad. I updated java assist to the latest version

**Comment by MajesticWaffle** [comment]
Were running a version of the injector that you compiled yourself, or was the problem occurring with an actual .jar release?

**Comment by erxson** [comment]
compiled my self

**Comment by erxson** [comment]
I added new commands and console+os commands

**Comment by MajesticWaffle** [comment]
Oh cool, if you throw it up on a fork that would be cool
