### ISSUE TITLE
[SUGGESTION] add this simple string obf

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#65]
https://github.com/shamanland/simple-string-obfuscator

Just use it for nickname

**Comment by MajesticWaffle** [comment]
I'll look into adding it. I'm assuming this is to avoid detection? 
I feel like anyone looking at a plugin's code hard enough to notice UUIDs would be able to see that this is blatantly a backdoor though.

**Comment by erxson** [comment]
Yes
