### ISSUE TITLE
Me Being Dumb

### ISSUE THREAD

**Issue by TheSkid4** [ThiccIndustries/Minecraft-Backdoor#66]
So no matter how much I tried to inject It just would work I tried injecting into some random plugin I got off of spigot and added my UUID With - and tried with out them eg e456-789-2094 or e456789102 and It just wouldnt work if anyone could help me that would be great my discord is Gingy#4459

**Comment by MajesticWaffle** [comment]
You should paste the UUID as is, including the '-'. Could you inject with debug mode on and send a server log?
