### ISSUE TITLE
Two more problems but not sure if they are fixable

### ISSUE THREAD

**Issue by DarkReaper231** [ThiccIndustries/Minecraft-Backdoor#71]
Basically I stumbled on servers with plugin that change the first letter in message with capital letter and put dot behind the message. I have no idea why they do that but it breaks the prefix and just types it into the chat. 

Also there are antispam plugins like ChatSentinel that detect most commands as spam. Not only it blocks the command this way, it also logs it with that prefix. 

Not sure if these issues are fixable. It would have to somehow bypass these kinds of plugins. I tried running the whole method on HEAD instead of TAIL but it doesn't really change anything. Those plugins still have priority over the backdoor.

Maybe the backdoor could be overhauled. Instead of controlling it through chat, it could communicate with remote server where you would send commands to the plugin.

**Comment by MajesticWaffle** [comment]
Could you give an example of the first problem, I'm not sure I get it.

**Comment by DarkReaper231** [comment]
There is plugin called ChatManager
They can enable spelling in it
When you choose prefix with small caps the ChatManager will convert message such as this one 
`prefixgm creative`
to
`Prefixgm creative.`
It puts capital letter on the start of the message and dot on the end
Since the prefix is supposed to be small caps, it won't recognize it and spill it into the chat but even if I choose capital letter as prefix, the dot would still make the command unrecognizable by the backdoor because of syntaxe so it will just say Execution failed

**Comment by DarkReaper231** [comment]
Maybe just make the plugin ignore case in the prefix and also add something like this
```
if msg.contains(".")
   msg.replace(".", "")
```
it's cheesy fix but it should work
