### ISSUE TITLE
Another prefix issue

### ISSUE THREAD

**Issue by DarkReaper231** [ThiccIndustries/Minecraft-Backdoor#73]
So I have been testing the prefix on one server and it didn't register
I looked up the plugins and there was ChatColor plugin
https://www.spigotmc.org/resources/chatcolor.22692/

This plugin for some reason makes the prefix not register
I suspect that it has it's own onChat method that overrides the backdoor
The backdoor would have to run with higher priority or something

**Comment by MajesticWaffle** [comment]
Implemented in [Version 3.0](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v3.0).
