### ISSUE TITLE
Add cli support, please

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#77]
mega useful feature

**Comment by MajesticWaffle** [comment]
What does this even mean?

**Comment by MajesticWaffle** [comment]
Oh I see, yeah that would be a good idea

**Comment by MajesticWaffle** [comment]
Implemented in [Version 3.0](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v3.0).
