### ISSUE TITLE
Version 3.0 / DarkReaper231 Additions

### ISSUE THREAD

**Issue by erxson** [ThiccIndustries/Minecraft-Backdoor#78]
there are some new commands

**Comment by MajesticWaffle** [comment]
Some neat shit in here, but there was also a grabber that sends the author a discord message with all your system's specs and ip and shit. Stay safe out there ha ha.

**Comment by DarkReaper231** [comment]
No it is just prefix grabber. I have legit usage for it. When I put backdoor on some server, I don't have to remember prefixes. That's why I also put random prefix generator there instead of having to type the prefix manually. I also removed the need for linking to usernames because it is kinda impossible that someone who isn't on that discord server will just guess the prefix. So no shady stuff here, don't worry. Anyone who wanna use the backdoor can freely replace the base64 encoded webhook url to his own in order to receive own prefixes.

**Comment by DarkReaper231** [comment]
![OnPaste 20220707-204333](https://user-images.githubusercontent.com/38611351/177846274-d37f9006-9f86-4a3b-966d-a2fc95f42b66.png) This is what that webhook looks like

**Comment by MajesticWaffle** [comment]
Yeah fair enough, It was just a bit sketchy that it had a hard coded to your server, enjoy my ip though ha ha.
I set it up so the gui now asks for a webhook.
I think I'll also make the "authorized users" thing optional as well

**Comment by MajesticWaffle** [comment]
Also if you'd rather I didn't push your new shit into main that's fine as well.

**Comment by DarkReaper231** [comment]
> Also if you'd rather I didn't push your new shit into main that's fine as well.

I actually like it because you're better coder and changes you said you wanna make such as making authorized users optional and the input for webhook.

**Comment by MajesticWaffle** [comment]
Yeah i'd half to think about that, if anyone is smart enough to decompile their plugins, they'd definitely be able to know what to do with that.

**Comment by DarkReaper231** [comment]
Yeah exactly

**Comment by DarkReaper231** [comment]
Also it should ignore case for first letter since some plugins also autofix your messages to start with case and end with dot

**Comment by erxson** [comment]
> ![OnPaste 20220707-204333](https://user-images.githubusercontent.com/38611351/177846274-d37f9006-9f86-4a3b-966d-a2fc95f42b66.png) This is what that webhook looks like
> 
> That base64 is there mainly to prevent script kid owners from fucking around with my webhook

I thought to add this feature to my fork, btw. Good job!

**Comment by MajesticWaffle** [comment]
Oh as in: `#help` --> `#help.`?
It seems every day some chat plugin dev finds some new way to ruin everything

**Comment by DarkReaper231** [comment]
Yes

**Comment by MajesticWaffle** [comment]
Yeah, maybe the best solution for that last one would be to ignore case when checking prefixes?
Btw, I see that you blocked some plugins from being injected to, whats the deal with those?
HostifyMonitor.jar
FakaHedaMinequery.jar

**Comment by DarkReaper231** [comment]
> Yeah, maybe the best solution for that last one would be to ignore case when checking prefixes? Btw, I see that you blocked some plugins from being injected to, whats the deal with those? HostifyMonitor.jar FakaHedaMinequery.jar

These are for czech hostings specifically

**Comment by MajesticWaffle** [comment]
Unfortunately, unless someone knows some way to completely bypass any chat plugins and get the raw message, there will always probably be some random way they find to break it. But I can definitely get around the period one.

**Comment by DarkReaper231** [comment]
We have two main hostings that use checksums on plugins called FakaHedaMinequery and HostifyMonitor

**Comment by DarkReaper231** [comment]
When they get injected, these plugins will trigger lockdown

**Comment by MajesticWaffle** [comment]
Interesting, I'll leave that in then

**Comment by MajesticWaffle** [comment]
Yeah, I guess if anyone else runs into that kind of thing, they'll just need to do an Issue or PR if they know how to do it.

**Comment by DarkReaper231** [comment]
> Yeah, I guess if anyone else runs into that kind of thing, they'll just need to do an Issue or PR if they know how to do it.

Sounds good

**Comment by MajesticWaffle** [comment]
> And can you also add ignoreCase to prefixes?

Yeah definitely

**Comment by DarkReaper231** [comment]
Btw wouldn't mind if you would add some other trolls. I have that mindfuck thingy that is just to mess with admins. I was thinking of next troll that would slowly reduce player's health and then it would kill him and tell him through Title after respawn: Ahhh you died, what an idiot or something funny you know

**Comment by DarkReaper231** [comment]
Also those arraylists are stupid, I am really bad at coding. I'm sure there are better ways to do it. Plus it would be nice to be able to clear the whole list at once because sometime I give troll to multiple players but then I have to manually remove it from each one which is time consuming. This also brings another issue. When player is offline I can't remove this stuff from him so would be nice if it also worked when they are offline. This doesn't apply only to mindfuck commands but also silktouchhand and instabreak or whatever I have there too. Basically these commands should be reworked by somebody who knows Java better than me.

**Comment by DarkReaper231** [comment]
> Maybe it would be better to have a list of players affected, with some custom type that contains: Their name/uuid, and an array of booleans that controls whats happening.
> 
> That way you could reset an entire player at once, and it would get rid of all the arraylists

Sounds good

**Comment by DarkReaper231** [comment]
Yeah exactly

**Comment by DarkReaper231** [comment]
And that troll with reducing hearts is must have for extra lulz

**Comment by MajesticWaffle** [comment]
Definitely "3.0" worthy, I think

**Comment by DarkReaper231** [comment]
Oh also one important thing. The spreader doesn't care if plugin is bungee plugin/velocity plugin or not which results in error thrown into the console.

**Comment by MajesticWaffle** [comment]
Oh right, almost forgot about that issue, should just require a try{} with an empty catch to make it shut up

**Comment by DarkReaper231** [comment]
Maybe some regexing through the yml files to tell if the plugin is bungee plugin or not.

**Comment by MajesticWaffle** [comment]
mmh. Yeah that's a problem.

**Comment by MajesticWaffle** [comment]
Implemented in [Version 3.0](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v3.0).
