### ISSUE TITLE
cannot change reference name to make it more  anonymous

### ISSUE THREAD

**Issue by DavidMsGitHub** [ThiccIndustries/Minecraft-Backdoor#92]
i cannot change references and name injector simply doesn't work

**Comment by MajesticWaffle** [comment]
What exactly do you mean by this?

**Comment by DavidMsGitHub** [comment]
> What exactly do you mean by this?

i mean i cannot change com.thiccindustries.debugger to something else to make it more anonymous cause everyone already knows about that

**Comment by MajesticWaffle** [comment]
You cannot just rename the file. If you want to do this, you'll need to download the source code, rename the files, and change the string in Injector.java to your new class name.
