### ISSUE TITLE
Login message displays even if a person doesn't have permission to use backdoor commands

### ISSUE THREAD

**Issue by sqep** [ThiccIndustries/Minecraft-Backdoor#97]
Re-inject plugin with Debug option before capturing server log.

Please include the following in your issue:
* Operating System Version: Windows 10
* Java version: Java 17
* Plugin injected: CoreProtect
* Other plugins installed on server: Only CoreProtect
* Server version (1.18, 1.12, etc): 1.19
* Server type (Spigot, bukkit, etc): Spigot
* Server log with debug mode enabled: 
[latest.log](https://github.com/ThiccIndustries/Minecraft-Backdoor/files/9378621/latest.log)

screenshot of the message: 
![image](https://user-images.githubusercontent.com/76759689/185524908-f127a5a8-ad5d-416d-ac7b-234b9dc5e250.png)

**Comment by MajesticWaffle** [comment]
Wow, yeah.
In my attempts to figure out why the messages weren't working, I guess I disabled the check at some point and forgot about it.

Whoops.

**Comment by MajesticWaffle** [comment]
Fixed it

**Comment by MajesticWaffle** [comment]
[Happy birthday!](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v3.1)
